### ISSUE TITLE
Android - Dateipfade

### ISSUE THREAD

**Issue by JonLit** [JonLit/PointMaze#1]
Beim Speichern und laden gibt's den Fehler 

java.lang.IllegalArgumentException: File /data/user/0/com.calsignlabs.apde.sketchpreview/files\save.txt contains a path separator
	at android.app.ContextImpl.makeFilename(ContextImpl.java:2466)
	at android.app.ContextImpl.openFileInput(ContextImpl.java:529)
	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:195)
	at processing.core.PSurfaceNone.openFileInput(PSurfaceNone.java:331)
	at processing.core.PApplet.createInputRaw(PApplet.java:5081)
	at processing.core.PApplet.createInput(PApplet.java:4889)
	at processing.core.PApplet.loadStrings(PApplet.java:5194)
	at processing.test.point_maze_mobile.Point_Maze_mobile_beta.loadLevel(Point_Maze_mobile_beta.java:275)
	at processing.test.point_maze_mobile.Point_Maze_mobile_beta.setup(Point_Maze_mobile_beta.java:368)
	at processing.core.PApplet.handleDraw(PApplet.java:1801)
	at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:471)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:503)
java.lang.IllegalArgumentException: File /data/user/0/com.calsignlabs.apde.sketchpreview/files\save.txt contains a path separator
	at android.app.ContextImpl.makeFilename(ContextImpl.java:2466)
	at android.app.ContextImpl.openFileInput(ContextImpl.java:529)
	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:195)
	at processing.core.PSurfaceNone.openFileInput(PSurfaceNone.java:331)
	at processing.core.PApplet.createInputRaw(PApplet.java:5081)
	at processing.core.PApplet.createInput(PApplet.java:4889)
	at processing.core.PApplet.loadStrings(PApplet.java:5194)
	at processing.test.point_maze_mobile.Point_Maze_mobile_beta.loadLevel(Point_Maze_mobile_beta.java:275)
	at processing.test.point_maze_mobile.Point_Maze_mobile_beta.setup(Point_Maze_mobile_beta.java:368)
	at processing.core.PApplet.handleDraw(PApplet.java:1801)
	at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:471)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:503)

**Comment by JonLit** [comment]
fixed, Android processing mag wohl dataPath() nicht
